### ISSUE TITLE
initial thoughts, not a grade yet

### ISSUE THREAD

**Issue by timm** [Arjun-Code-Knight/csc510-se-project#1]
_(@shaowns, fyi, some thoughts but no grade yet. please note item 2, below.)_

nice data collection and analysis job

never actually thought about it before, but yes i do spend a lot time messing around with screen snaps

two things to note, going downstream,
1. There is the problem of maintaining attribution with the screen snaps. if i do a lot of internet screen snapping, i can recall work out where the original material came from. so,  2 months from now, if i want to use that snap in some public report, then i can't.
2. Early in Feb, please meet with me or the TA to check that your three proposed solutions are not too small. From here you have to do some non-trivial coding to address this problem. I just want to make sure that you have selected too small a problem to really show off the strengths of your group.

**Comment by botwithfeelings** [comment]
@sushmarchandran, @Arjun-Code-Knight, @amurark, @Ssukriti, could any of you please confirm that you met with the professor and discussed your three solutions, or you are looking forward to do so?

**Comment by Ssukriti** [comment]
@shaowns ,
Yes we met with the professor and discussed our three solutions. As per his suggestions, we have added more complexity to our solutions.

**Comment by botwithfeelings** [comment]
@Ssukriti, thanks. Closing this.
