### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by sushmarchandran** [Arjun-Code-Knight/csc510-se-project#30]
Create telemetry on Server Side

**Comment by Arjun-Code-Knight** [comment]
Need to work with the UI team to define contracts and finish the work

**Comment by Arjun-Code-Knight** [comment]
Created new services to cater login and sign up

**Comment by Arjun-Code-Knight** [comment]
created new services to handle the cross search

**Comment by Arjun-Code-Knight** [comment]
COmpleted after the meeting
