### ISSUE TITLE
Exploring APIS to upload images to amazon cloud

### ISSUE THREAD

**Issue by Ssukriti** [Arjun-Code-Knight/csc510-se-project#5]

**Comment by Arjun-Code-Knight** [comment]
@amurark  I have set up the server from my end. Only few tasks left out to complete. We can have a discussion and you can branch the code to add additional changes to it to support AWS.

**Comment by Arjun-Code-Knight** [comment]
AWS api's integration with server complete

**Comment by amurark** [comment]
Task completed, using java sdk for amazon aws integration.
