### ISSUE TITLE
setting up server

### ISSUE THREAD

**Issue by Ssukriti** [Arjun-Code-Knight/csc510-se-project#7]
set up server with mongodb

**Comment by Arjun-Code-Knight** [comment]
I have committed the base for the server code. It encompasses the initial support for the uploading and saving the files on the web server. It also uses tess4j api's to extract OCR from the images uploaded

**Comment by Arjun-Code-Knight** [comment]
The next task left out is to upload the files from our server into Amazon and store the token and links on Mongodb to maintain user specific data

**Comment by Arjun-Code-Knight** [comment]
https://sourceforge.net/projects/tess4j/ some really cool api's for OCR.. simple and sweet

**Comment by Arjun-Code-Knight** [comment]
Completed server Setup
